### ISSUE TITLE
Am I supposed to have noclip?

### ISSUE THREAD

**Issue by HyperBeast43** [danielesteban/blocks-editor-examples#1]
After exploring around, I'm seeing places where I supposedly parkour, and places where I supposedly block objects. I can't do either with noclip. Am I supposed to have this?

**Comment by danielesteban** [comment]
The desktop controls are just a hack for people who didn't have access to head mounted displays.
They were also used mostly for development.
The only real controls are the ones for VR.
I didn't even know how to keep the player out of the geometry at the time.
So I beleive the VR controls pull this off just by only allowing you to teleport or climb.
This is also a 2 year old project that I no longer mantain. So it's also prolly broken.

Thanks for checking it out, though.

**Comment by HyperBeast43** [comment]
oh it's for vr? i've gotta check this out, then!
